### PR TITLE
Update for v14

### PR DESCRIPTION
**Pull request by qrntz**

### CODE REVIEW

**Comment by alonswartz** [comment]
Good work! A few questions though:

1. Why the username change from admin to gitlab-admin? What migration error are you referring to?
2. The inithook would only restart gitlab if it was running. I suppose this was an optimization with sysvinit being synchronous and no longer needed due to systemd being asynchronous - just wanted to understand your rational?

**Comment by qrntz** [comment]
@alonswartz,

1. The Rake DB bootstrap process produced two warnings, one that the password is too short (remediated by changing «turnkey» to «turnkey1» to fit the 8 char limit), and one that the username is reserved (apparently, «admin» _is_ however weird that might be even though it's the only one in the database after the installation process). Changing it was the most obvious solution and from what I know, it won't affect much since the inithook sets the e-mail to log in with and the appliance's README recommends logging in using the e-mail as well.
2. Do you mean that the ExecError handling is no longer needed and the commands should Just Work now?

**Comment by alonswartz** [comment]
1. Thanks for the explanations.
2. What I meant was that the status command would return a non-zero exit code if gitlab wasn't running, which would mean we don't need to restart it. If it was running though, then the exit code would be 0, and we would restart it so the changes would take effect.

We should be good to go with what we have....

**Comment by qrntz** [comment]
Ah, I see. To be honest, I made an assumption there of sorts… but if systemd works as I remember it doing then indeed, it should be sufficient.

**Pull request merged**
